#!/usr/bin/env node
/**
 * report_generator.js — Generate a PDF report from an Umpire Coder event log
 *
 * Usage:
 *   node report_generator.js --json <path/to/events.json> [--out <output-dir>]
 *
 * Output:
 *   <out>/<Date>_<Competition>_report.pdf
 *
 * Requires:  npm install   (installs pdfkit)
 */

import { createWriteStream, existsSync, mkdirSync, readFileSync } from 'fs';
import { resolve, join } from 'path';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const PDFDocument = require('pdfkit');

// ── CLI args ──────────────────────────────────────────────────────────────────

function parseArgs() {
  const args = process.argv.slice(2);
  const get  = (flag) => { const i = args.indexOf(flag); return i !== -1 ? args[i + 1] : null; };
  const jsonPath = get('--json');
  const outDir   = get('--out');
  if (!jsonPath) {
    console.error('Usage: node report_generator.js --json <events.json> [--out <output-dir>]');
    process.exit(1);
  }
  return { jsonPath: resolve(jsonPath), outDir };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function sanitiseFilename(str) {
  return (str || 'unknown')
    .replace(/[^a-zA-Z0-9_\- ]/g, '')
    .replace(/\s+/g, '_')
    .substring(0, 60);
}

function reportFilename(meta) {
  const date = (meta.date || 'unknown-date').replace(/\//g, '-');
  const comp = sanitiseFilename(meta.competition || 'match');
  return `${date}_${comp}_report.pdf`;
}

function countBy(events, key) {
  return events.reduce((acc, ev) => {
    const v = ev[key] || 'Unknown';
    acc[v] = (acc[v] || 0) + 1;
    return acc;
  }, {});
}

// ── PDF helpers ───────────────────────────────────────────────────────────────

const COLOURS = {
  brand:       '#1a3a8f',
  brandLight:  '#e8edf8',
  headerBg:    '#1a3a8f',
  rowEven:     '#f4f6fb',
  rowOdd:      '#ffffff',
  muted:       '#6b7280',
  border:      '#d1d5db',
  danger:      '#b91c1c',
  text:        '#111827',
};

const MARGIN = 50;
const PAGE_W = 595.28; // A4

function writePDF(doc, meta, events) {
  const umpires   = [meta.umpire1, meta.umpire2].filter(Boolean);
  const allTags   = [...new Set(events.map(e => e.tag).filter(Boolean))].sort();

  // ── Cover / header ──────────────────────────────────────────────────────────
  doc.rect(0, 0, PAGE_W, 80).fill(COLOURS.headerBg);
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(20)
     .text('Umpire Performance Report', MARGIN, 24, { width: PAGE_W - MARGIN * 2 });
  doc.fontSize(10).font('Helvetica').fillColor('#ccd6f6')
     .text('Generated by Umpire Coder', MARGIN, 50, { width: PAGE_W - MARGIN * 2 });

  let y = 100;

  // ── Match metadata ──────────────────────────────────────────────────────────
  doc.fillColor(COLOURS.brand).font('Helvetica-Bold').fontSize(13)
     .text('Match Details', MARGIN, y);
  y += 18;

  const metaRows = [
    ['Umpires',     umpires.join('  &  ') || '—'],
    ['Date',        meta.date        || '—'],
    ['Competition', meta.competition || '—'],
    ['Venue',       meta.venue       || '—'],
    ['Total events', String(events.length)],
  ];

  for (const [label, value] of metaRows) {
    doc.fillColor(COLOURS.muted).font('Helvetica').fontSize(10)
       .text(label + ':', MARGIN, y, { width: 120, continued: false });
    doc.fillColor(COLOURS.text).font('Helvetica-Bold').fontSize(10)
       .text(value, MARGIN + 125, y, { width: PAGE_W - MARGIN * 2 - 125 });
    y += 16;
  }

  y += 10;
  doc.moveTo(MARGIN, y).lineTo(PAGE_W - MARGIN, y).strokeColor(COLOURS.border).lineWidth(0.5).stroke();
  y += 16;

  // ── Summary ─────────────────────────────────────────────────────────────────
  doc.fillColor(COLOURS.brand).font('Helvetica-Bold').fontSize(13).text('Summary', MARGIN, y);
  y += 20;

  for (const umpire of umpires.length ? umpires : ['(all)']) {
    const umpireEvents = umpires.length
      ? events.filter(e => e.umpire === umpire)
      : events;

    doc.fillColor(COLOURS.text).font('Helvetica-Bold').fontSize(11).text(umpire, MARGIN, y);
    y += 15;

    const tagCounts = countBy(umpireEvents, 'tag');
    if (Object.keys(tagCounts).length === 0) {
      doc.fillColor(COLOURS.muted).font('Helvetica').fontSize(10).text('No events', MARGIN + 10, y);
      y += 14;
    } else {
      for (const tag of allTags) {
        const count = tagCounts[tag] || 0;
        if (count === 0) continue;
        const bar = '█'.repeat(Math.min(count, 30));
        doc.fillColor(COLOURS.muted).font('Helvetica').fontSize(10)
           .text(`${tag}`, MARGIN + 10, y, { width: 160, continued: false });
        doc.fillColor(COLOURS.brand).font('Helvetica').fontSize(10)
           .text(`${bar}  ${count}`, MARGIN + 175, y, { width: PAGE_W - MARGIN - 175 });
        y += 14;
      }
    }
    y += 8;
  }

  y += 4;
  doc.moveTo(MARGIN, y).lineTo(PAGE_W - MARGIN, y).strokeColor(COLOURS.border).lineWidth(0.5).stroke();
  y += 16;

  // ── Event table ─────────────────────────────────────────────────────────────
  doc.fillColor(COLOURS.brand).font('Helvetica-Bold').fontSize(13).text('All Events', MARGIN, y);
  y += 20;

  // Column widths (must sum to PAGE_W - 2*MARGIN = 495)
  const cols = {
    num:     30,
    time:    68,
    live:    68,
    umpire:  110,
    tag:     105,
    notes:   114,  // remainder
  };

  const ROW_H = 16;
  const HEADER_H = 18;

  function tableHeader(yPos) {
    doc.rect(MARGIN, yPos, PAGE_W - MARGIN * 2, HEADER_H).fill(COLOURS.headerBg);
    let x = MARGIN + 4;
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(9);
    doc.text('#',           x, yPos + 4, { width: cols.num    - 4 }); x += cols.num;
    doc.text('Rec. Time',   x, yPos + 4, { width: cols.time   - 4 }); x += cols.time;
    doc.text('Live Time',   x, yPos + 4, { width: cols.live   - 4 }); x += cols.live;
    doc.text('Umpire',      x, yPos + 4, { width: cols.umpire - 4 }); x += cols.umpire;
    doc.text('Tag',         x, yPos + 4, { width: cols.tag    - 4 }); x += cols.tag;
    doc.text('Notes',       x, yPos + 4, { width: cols.notes  - 4 });
    return yPos + HEADER_H;
  }

  y = tableHeader(y);

  for (let i = 0; i < events.length; i++) {
    const ev = events[i];

    // New page if needed (leave room for at least one row)
    if (y + ROW_H > doc.page.height - 50) {
      doc.addPage();
      y = MARGIN;
      y = tableHeader(y);
    }

    const bgColour = i % 2 === 0 ? COLOURS.rowEven : COLOURS.rowOdd;
    doc.rect(MARGIN, y, PAGE_W - MARGIN * 2, ROW_H).fill(bgColour);

    let x = MARGIN + 4;
    doc.fillColor(COLOURS.muted).font('Helvetica').fontSize(8)
       .text(String(i + 1), x, y + 4, { width: cols.num - 4 }); x += cols.num;

    doc.fillColor(COLOURS.text).font('Helvetica-Bold').fontSize(8)
       .text(ev.timestamp_elapsed      || '—', x, y + 4, { width: cols.time - 4 }); x += cols.time;
    doc.fillColor(COLOURS.muted).font('Helvetica').fontSize(8)
       .text(ev.timestamp_elapsed_live || '—', x, y + 4, { width: cols.live - 4 }); x += cols.live;
    doc.fillColor(COLOURS.text).font('Helvetica').fontSize(8)
       .text(ev.umpire  || '—', x, y + 4, { width: cols.umpire - 4 }); x += cols.umpire;
    doc.fillColor(COLOURS.brand).font('Helvetica-Bold').fontSize(8)
       .text(ev.tag     || '—', x, y + 4, { width: cols.tag    - 4 }); x += cols.tag;
    doc.fillColor(COLOURS.muted).font('Helvetica').fontSize(8)
       .text(ev.notes   || '',  x, y + 4, { width: cols.notes  - 4 });

    y += ROW_H;
  }

  // ── Footer ──────────────────────────────────────────────────────────────────
  const pageCount = doc.bufferedPageRange
    ? doc.bufferedPageRange().count
    : 1;

  const footerY = doc.page.height - 30;
  doc.fillColor(COLOURS.muted).font('Helvetica').fontSize(8)
     .text(
       `Umpire Coder  ·  ${new Date().toISOString().slice(0, 10)}  ·  ${events.length} event(s)`,
       MARGIN, footerY,
       { width: PAGE_W - MARGIN * 2, align: 'center' }
     );
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main() {
  const { jsonPath, outDir } = parseArgs();

  if (!existsSync(jsonPath)) {
    console.error(`JSON not found: ${jsonPath}`);
    process.exit(1);
  }

  const raw    = JSON.parse(readFileSync(jsonPath, 'utf8'));
  const meta   = raw.match  || {};
  const events = raw.events || [];

  const baseDir  = outDir ? resolve(outDir) : resolve(jsonPath, '..');
  mkdirSync(baseDir, { recursive: true });

  const pdfPath = join(baseDir, reportFilename(meta));
  const doc     = new PDFDocument({ autoFirstPage: true, size: 'A4', margin: MARGIN });
  const stream  = createWriteStream(pdfPath);

  doc.pipe(stream);
  writePDF(doc, meta, events);
  doc.end();

  stream.on('finish', () => {
    console.log(`Report written → ${pdfPath}`);
  });
  stream.on('error', (err) => {
    console.error('Failed to write PDF:', err.message);
    process.exit(1);
  });
}

main();
